# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.13.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - export PORT="4090"
          - export TEST_PORT="4091"
          - export JWT_TOKEN_SECRET="$t3eg34yEWRG£$%UY"
          - export DB="mongodb://127.0.0.1/clientLicenses"
          - export DEFAULT_CLIENT_NAME="FutureProof"
          - export LOG_LEVEL="debug"
          - npm test
        services: 
          - mongo 
definitions: 
  services: 
    mongo: 
      image: mongo