version: "3.7"
services:
  scrabble-api:
    image: scrabble-api
    container_name: scrabble-api
    restart: always
    build: .
    ports:
      - "4090:4090"
    environment:
      - 'JWT_TOKEN_SECRET=@£%2tq4Q£43qy'
      - PORT=4090
      - LOG_LEVEL=info
    volumes:
      - ~//data:/app/data/