version: "3.7"
services:
  scrabble-api:
    environment:
      - PORT=4090
      - TEST_PORT=4091
      - "JWT_TOKEN_SECRET=@£tg23t@y@!@£^YQ"
      - DB=mongodb://scrabble-db/scrabble
  scrabble-db:
    volumes:
      - ~//data:/data/
networks:
  default:
    external:
      name: scrabble